### ISSUE TITLE
Distributor set up script problem 

### ISSUE THREAD

**Issue by pbambusek** [MewsSystems/public#21]
On behalf of Urban House:

Problem at the Urban House website.
The error is that the booking flow show all rooms - not the ones which have elected in the script. And also in a wrong order.
They have blocked out some of the rooms, so if you try to book a room AFTER march 27 2018, you will get an option to book bed in single room, and this is not part of the script. The Room Identifier I mean.

The error has been really tough to figure out, but the devs has asked me to pass on this message:
It seems the data is being sent and received properly. We compared the results with Reservations Time Line and everything is in order, so it's hard for us to do anything else in that matter. If you're getting wrong or unexpected results it seems that the only way is to contact the Mews people. The only thing we can do is to remove all deprecated options but we would need the Mews to have a look at the script and tell us what should be removed. For now we removed only some items we were 100% sure about.

The Mews.Distributor constructor and its callback should be working fine now and a form on the room-categories should normally lead to a chosen room - you just need to fill room-id of some of them.

The Script they mention can be found here:
http://urbanhouse.me/wp-content/themes/UrbanHouse/js/script.js http://urbanhouse.me/wp-content/themes/UrbanHouse/js/script.js

**Comment by pbambusek** [comment]
What I've found out is that the client api is not defensive enough, and allows Distributor to end up in incosistent state, i.e. changing date when you left the Distributor on rates step.

Since you always change end date on generic open, odds are high that this will happen. In that case the execution will fail and rooms filter is not set at all. It might be the cause of the problem you're experiencing.

You can try it for yourself before the fix gets to production, by removing line 388 (`distributor.setEndDate(endDate);`). Also be noted that you can simply use an option http://mewssystems.github.io/public/content/developers/distributor/widget.html#daysInterval to do exactly what you want.

Having deprecated options in constructor is not a big issue, they're simply disregarded. However, if you want to keep it clean, from what I see, you can remove those commented out and also `hashEvents`.

**Comment by crosenbech** [comment]
Hi @pbambusek 
We tried the suggested corrections - but still see the error. Could you check/test to see if we implemented them correctly?
Thank you

**Comment by crosenbech** [comment]
Any chance you could give me a tmeline of when the fix is live?

**Comment by jirihelmich** [comment]
Hello,

we cannot share any specific date, I can just assure you that it's at the top of our development pipeline as we address bugs before we do anything else.

We currently have a few releases each week and this should not take long to fix if we do not find any thing unexpected. If we do, we will let you know.

**Comment by pbambusek** [comment]
The fix solves the use of api, which in your case prevented `setRooms` call to be executed. With use of `daysInterval` this is no longer problem.

However, I can see some logic problems in your script. You set the list of rooms only if there is no `singleId`, in other words, if I don't click on book room link first. Why do you do so? I can then got back to Rooms step and see all the rooms.

Second thing I've noticed is that some of the rooms link doesn't have an id set at all, i.e right the first ShoeBox.

> They have blocked out some of the rooms, so if you try to book a room AFTER march 27 2018, you will get an option to book bed in single room, and this is not part of the script. The Room Identifier I mean.

This I don't understand. Could you explain this little bit more to me? I don't see anything like this anywehere in the script. Also, if you want to block rooms from being booked, there should be a restriction set in Commander, not room filter in Distributor.

**Comment by pbambusek** [comment]
I guess this is solved.

**Comment by pbambusek** [comment]
@crosenbech Could I get your status on this? Hotel wrote us that this is still not solved.

**Comment by crosenbech** [comment]
@pbambusek Hi Petr,

currently we are not concentrating on the subpage room-categories, but only on the main booking button in the top of the page. 
We  have set daysInterval after disabling setting an end date with every open.  But the rooms are still listed in a wrong order, and we can also still see rooms that are not supposed to be there. 
Unfortunately it is not an option to block out the rooms in the commander - Urban House does not want to do that.

Regarding my suggestion to try and book a room AFTER March 27 2018 - you need to do that via the front end. It is not a part of the script.

**Comment by pbambusek** [comment]
@crosenbech I guess you mean that order is different than order based on the order of room ids in `roomFilter`, is that right? Because that's completely correct, the `roomFilter` is just set of ids used as filter. It's not meant to work as ordering. The order is determined by an ordering property of room categories set in Commander.

We're currently preparing a new feature, that will allow you to configure different order in Commander and Distributor, so if this is the case, you'll need to wait for it to be released. Or change the current order in Commander.

The `Bed in single room (shoebox)` has an id `bb8ed1de-7424-4386-9756-cefde44a1e9a`, which is part of the `roomFilter` you set in the script, so there is no bug. The only way you could have had seen it was the incorrect setting of `roomFilter` for some cases as described.

**Comment by crosenbech** [comment]
@pbambusek thank you! I will let urban house know they can set the order of rooms within the Commander.

I have removed Bed in single room (shoebox) with id bb8ed1de-7424-4386-9756-cefde44a1e9a from the roomFilter. But it still shows up in the booking flow after march 27 2018. Weird no?

**Comment by pbambusek** [comment]
@crosenbech I don't see it there. Are you sure you're not mistaking it with "Single room (shoebox)" as the whole room, not bed, with id `895ecab9-85d6-43c1-98c5-42144ed945a7`?

**Comment by pbambusek** [comment]
@crosenbech I'm considering it resolved. If not the case, please reopen with comment.
